In [20]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import time

In [21]:
import sqlite3
import numpy as np

In [22]:
for i in range(0,30):
    print(i)
    time.sleep(5)

0
1
2
3


KeyboardInterrupt: 

In [24]:
# Get from DB
while(1):
    conn = sqlite3.connect('C:/Users/akash/Documents/MLProjects/MLProject2/simulate/fruits.db')
    df = pd.read_sql("SELECT * FROM FRUITS", conn)
    conn.close()
    
    # Define X and y
    
    X = df[['MASS','WIDTH','HEIGHT','COLOUR']]
    y = df['FRUITLABEL']
    print(np.array(y).astype('int32'))

    time.sleep(5)

[4 2 1 ... 2 3 1]
[3 3 1 ... 1 1 1]
[2 3 3 ... 4 4 4]


KeyboardInterrupt: 

In [38]:
import os
import pickle

In [49]:
### Load latest model
path = 'C:/Users/akash/Documents/MLProjects/LiveData/ModelRegistry/MLproject2/'
pkl_files = [file for file in os.listdir(path) if file.endswith('.pkl')]
# Sort the list of files by modification time (latest first)
pkl_files.sort(key=lambda x: os.path.getmtime(os.path.join(path, x)), reverse=True)
# Load the latest .pkl file
latest_pkl_file = pkl_files[0]
with open(path+latest_pkl_file, 'rb') as file:
    loaded_model = pickle.load(file)
logreg = loaded_model

In [50]:
scaler = MinMaxScaler()
X = np.array(X)
X = scaler.fit_transform(X)

In [51]:
logreg.predict(X)

array([1, 1, 4, ..., 3, 4, 1], dtype=int64)

In [52]:
logreg.score(X,y)

0.0

In [53]:
y

0          apple
1          apple
2       mandarin
3       mandarin
4          lemon
          ...   
2995    mandarin
2996       apple
2997       lemon
2998    mandarin
2999      orange
Name: FRUIT, Length: 3000, dtype: object